// Code goes here

function app($scope) {
  $scope.search = '';
  $scope.select = function( font, height, close ){
    for(var i=0;i<$scope.data.length;i++) {
      $scope.data[i].height = 0;
      $scope.data[i]['class']= '';
      $scope.data[i].badge= false;

      if( !close && font === $scope.data[i] ) {
        $scope.data[i].selected = !$scope.data[i].selected;

        console.log($scope.data[i].selected);

        if($scope.data[i].selected===true) {
          $scope.data[i].height = height || 500;
          $scope.data[i]['class']='og-expanded';
        }
      } else  {
        $scope.data[i].selected = false;
      }
    }
    font.badge = true;
  };

  $scope.options = {
    'borderWidth': 3,
    'borderColor': '#ffbb00',
    'backgroundColor': '#cccccc',
    'fontColor': '#666666'
  };

  $scope.scm = new ColorScheme;

  $scope.randomColors = function() {
      var seed = 1 + Math.floor(Math.random() * 5000);
      $scope.scm.from_hue(seed)
         .scheme('triade')
         .distance(0.1)
         .add_complement(false)
         .variation('pastel')
         .web_safe(false);

      var colors = $scope.scm.colors();
      $scope.options.borderColor= '#'+colors[0];
      $scope.options.backgroundColor='#'+colors[2];
      $scope.options.fontColor='#'+colors[5];
  };

  $scope.randomColors();

  $scope.data = [
      {'name':'fa-adjust','searchText':'fa-adjust adjust circle accommodate accustom adapt alter conform fine-tune fix modify', 'badge': true},
      {'name':'fa-adn','searchText':'fa-adn adn'},
      {'name':'fa-align-center','searchText':'fa-align-center align-center text format write edit adjust middle'},
      {'name':'fa-align-justify','searchText':'fa-align-justify align-justify text format write edit adjust'},
      {'name':'fa-align-left','searchText':'fa-align-left align-left text format write edit adjust'},
      {'name':'fa-align-right','searchText':'fa-align-right align-right text format write edit adjust'},
      {'name':'fa-ambulance','searchText':'fa-ambulance ambulance medical health box rescue transport ems hospital'},
      {'name':'fa-anchor','searchText':'fa-anchor anchor ship ballast'},
      {'name':'fa-android','searchText':'fa-android android'},
      {'name':'fa-angle-double-down','searchText':'fa-angle-double-down angle-double-down arrow direction'},
      {'name':'fa-angle-double-left','searchText':'fa-angle-double-left angle-double-left arrow direction previous'},
      {'name':'fa-angle-double-right','searchText':'fa-angle-double-right angle-double-right arrow direction next'},
      {'name':'fa-angle-double-up','searchText':'fa-angle-double-up angle-double-up arrow direction'},
      {'name':'fa-angle-down','searchText':'fa-angle-down angle-down arrow direction'},
      {'name':'fa-angle-left','searchText':'fa-angle-left angle-left arrow direction previous'},
      {'name':'fa-angle-right','searchText':'fa-angle-right angle-right arrow direction next'},
      {'name':'fa-angle-up','searchText':'fa-angle-up angle-up arrow direction'},
      {'name':'fa-apple','searchText':'fa-apple apple fruit nature tree plant'},
      {'name':'fa-archive','searchText':'fa-archive archive box case container storage files chronicles vault cache'},
      {'name':'fa-arrow-circle-down','searchText':'fa-arrow-circle-down arrow-circle-down arrow direction'},
      {'name':'fa-arrow-circle-left','searchText':'fa-arrow-circle-left arrow-circle-left arrow direction empty previous'},
      {'name':'fa-arrow-circle-o-down','searchText':'fa-arrow-circle-o-down arrow-circle-o-down arrow direction empty'},
      {'name':'fa-arrow-circle-o-left','searchText':'fa-arrow-circle-o-left Arrow-circle-o-left direction box empty previous'},
      {'name':'fa-arrow-circle-o-right','searchText':'fa-arrow-circle-o-right Arrow-circle-o-right direction empty next'},
      {'name':'fa-arrow-circle-o-up','searchText':'fa-arrow-circle-o-up arrow-circle-o-up arrow direction'},
      {'name':'fa-arrow-circle-right','searchText':'fa-arrow-circle-right arrow-circle-right arrow direction next'},
      {'name':'fa-arrow-circle-up','searchText':'fa-arrow-circle-up arrow-circle-up arrow direction'},
      {'name':'fa-arrow-down','searchText':'fa-arrow-down arrow-down arrow direction'},
      {'name':'fa-arrow-left','searchText':'fa-arrow-left arrow-left arrow direction previous'},
      {'name':'fa-arrow-right','searchText':'fa-arrow-right arrow-right arrow direction next'},
      {'name':'fa-arrow-up','searchText':'fa-arrow-up arrow-up arrow direction'},
      {'name':'fa-arrows','searchText':'fa-arrows arrows arrow direction'},
      {'name':'fa-arrows-alt','searchText':'fa-arrows-alt arrows-alt arrow direction'},
      {'name':'fa-arrows-h','searchText':'fa-arrows-h arrows-h arrow direction left right'},
      {'name':'fa-arrows-v','searchText':'fa-arrows-v arrows-v arrow direction up down'},
      {'name':'fa-asterisk','searchText':'fa-asterisk asterisk star bullet caret dagger leaders punctuation'},
      {'name':'fa-backward','searchText':'fa-backward backward media player video audio'},
      {'name':'fa-ban','searchText':'fa-ban ban no boycott censorship embargo injuction prohibition refusal restriction stop'},
      {'name':'fa-bar-chart-o','searchText':'fa-bar-chart-o bar-chart-o graph'},
      {'name':'fa-barcode','searchText':'fa-barcode barcode scan'},
      {'name':'fa-bars','searchText':'fa-bars bars lines'},
      {'name':'fa-beer','searchText':'fa-beer beer drink glass cup liquid ale brew hops lager stout amber barley brewski mug'},
      {'name':'fa-bell','searchText':'fa-bell bell sound music alarm buzzer chime ding dong gong ringer siren'},
      {'name':'fa-bell-o','searchText':'fa-bell-o bell-o sound music'},
      {'name':'fa-bitbucket','searchText':'fa-bitbucket bitbucket box'},
      {'name':'fa-bitbucket-square','searchText':'fa-bitbucket-square bitbucket-square'},
      {'name':'fa-bitcoin','searchText':'fa-bitcoin bitcoin currency money transaction economy btc cash fund payment waelth bucks coin finance funds gold riches treasure tender'},
      {'name':'fa-bold','searchText':'fa-bold bold text format write edit'},
      {'name':'fa-bolt','searchText':'fa-bolt bolt electricity energy lightning flash power'},
      {'name':'fa-book','searchText':'fa-book book edition fiction magazine manual novel paperback publication textbook voumn writing reader print'},
      {'name':'fa-bookmark','searchText':'fa-bookmark bookmark favourite favorite clip holder marker slip'},
      {'name':'fa-bookmark-o','searchText':'fa-bookmark-o bookmark-o favourite favorite clip holder marker slip'},
      {'name':'fa-briefcase','searchText':'fa-briefcase briefcase case container carry storage baggage attache'},
      {'name':'fa-bug','searchText':'fa-bug bug insect animal nature ant beetle flea pest cootie gnat vermin breakdown defect error failure flaw problem trouble hitch issue'},
      {'name':'fa-building-o','searchText':'fa-building-o building-o skyscraper architecture construction home house hut domicile structure'},
      {'name':'fa-bullhorn','searchText':'fa-bullhorn bullhorn megaphone tool megaphone amplifier'},
      {'name':'fa-bullseye','searchText':'fa-bullseye bullseye target center omphalos'},
      {'name':'fa-calendar','searchText':'fa-calendar calendar date agenda diary journal timetable day time chronology'},
      {'name':'fa-calendar-o','searchText':'fa-calendar-o calendar-o date agenda diary journal timetable day time chronology'},
      {'name':'fa-camera','searchText':'fa-camera camera photo polariod 35mm kodak'},
      {'name':'fa-camera-retro','searchText':'fa-camera-retro camera-retro photo box empty'},
      {'name':'fa-caret-down','searchText':'fa-caret-down caret-down arrow direction'},
      {'name':'fa-caret-left','searchText':'fa-caret-left caret-left arrow direction previous'},
      {'name':'fa-caret-right','searchText':'fa-caret-right caret-right arrow direction box empty next'},
      {'name':'fa-caret-square-o-down','searchText':'fa-caret-square-o-down caret-square-o-down arrow direction box empty'},
      {'name':'fa-caret-square-o-left','searchText':'fa-caret-square-o-left Caret-square-o-left arrow square box'},
      {'name':'fa-caret-square-o-right','searchText':'fa-caret-square-o-right caret-square-o-right arrow direction box empty next'},
      {'name':'fa-caret-square-o-up','searchText':'fa-caret-square-o-up caret-square-o-up arrow direction'},
      {'name':'fa-caret-up','searchText':'fa-caret-up caret-up arrow direction'},
      {'name':'fa-certificate','searchText':'fa-certificate certificate affidavit authentication authorization certification coupon credential deed diploma documentation guarantee license paper permit receipt ticket voucher warrant warranty'},
      {'name':'fa-chain','searchText':'fa-chain chain text format write edit sequence'},
      {'name':'fa-chain-broken','searchText':'fa-chain-broken chain-broken text format write edit'},
      {'name':'fa-check','searchText':'fa-check check tick ok approve accept favor agree confirm endorse okay permit sign'},
      {'name':'fa-check-circle','searchText':'fa-check-circle check-circle tick ok approve accept favor agree confirm endorse okay permit sign'},
      {'name':'fa-check-circle-o','searchText':'fa-check-circle-o check-circle-o tick ok box approve accept favor agree confirm endorse okay permit sign'},
      {'name':'fa-check-square','searchText':'fa-check-square check-square tick ok box box approve accept favor agree confirm endorse okay permit sign'},
      {'name':'fa-check-square-o','searchText':'fa-check-square-o check-square-o tick ok approve accept favor agree confirm endorse okay permit sign'},
      {'name':'fa-chevron-circle-down','searchText':'fa-chevron-circle-down chevron-circle-down arrow direction'},
      {'name':'fa-chevron-circle-left','searchText':'fa-chevron-circle-left chevron-circle-left arrow direction previous'},
      {'name':'fa-chevron-circle-right','searchText':'fa-chevron-circle-right chevron-circle-right arrow direction next'},
      {'name':'fa-chevron-circle-up','searchText':'fa-chevron-circle-up chevron-circle-up arrow direction'},
      {'name':'fa-chevron-down','searchText':'fa-chevron-down chevron-down arrow direction'},
      {'name':'fa-chevron-left','searchText':'fa-chevron-left chevron-left arrow direction previous'},
      {'name':'fa-chevron-right','searchText':'fa-chevron-right chevron-right arrow direction next'},
      {'name':'fa-chevron-up','searchText':'fa-chevron-up chevron-up arrow direction empty'},
      {'name':'fa-circle','searchText':'fa-circle circle shape'},
      {'name':'fa-circle-o','searchText':'fa-circle-o circle-o shape judge case'},
      {'name':'fa-clipboard','searchText':'fa-clipboard clipboard text format write edit notes points paste text format write edit repeat replicate reproduce transcribe clone ditto mirror duplicate'},
      {'name':'fa-clock-o','searchText':'fa-clock-o clock-o shape time chronolograph chronometer alarm timer hourglass ticker watch tick-tock'},
      {'name':'fa-cloud','searchText':'fa-cloud cloud weather fog gloom mist smog vapor frost'},
      {'name':'fa-cloud-download','searchText':'fa-cloud-download cloud-download file weather fog gloom mist smog vapor frost'},
      {'name':'fa-cloud-upload','searchText':'fa-cloud-upload cloud-upload file computer weather fog gloom mist smog vapor frost'},
      {'name':'fa-cny','searchText':'fa-cny cny currency money transaction economy cash fund payment waelth bucks coin finance funds gold riches treasure tender'},
      {'name':'fa-code','searchText':'fa-code code html brackets sourcecode'},
      {'name':'fa-code-fork','searchText':'fa-code-fork code-fork sourcecode'},
      {'name':'fa-coffee','searchText':'fa-coffee coffee drink glass liquid caffeine cappuccino espresso brew decaf decoction demitasse java mocha perk café lait cafe noir hot stuff jamocha joe'},
      {'name':'fa-cog','searchText':'fa-cog cog settings machine shape gear ratchet tooth transmission wheel configure setup'},
      {'name':'fa-cogs','searchText':'fa-cogs cogs settings machine shape gears ratchet tooth transmission wheel configure setup'},
      {'name':'fa-columns','searchText':'fa-columns columns text format write edit'},
      {'name':'fa-comment','searchText':'fa-comment comment discuss conversation message chat talk commentary criticism discussion mention note observation opinion remark review animadversion annotation backtalk buzz '},
      {'name':'fa-comment-o','searchText':'fa-comment-o comment-o discuss conversation message chat talk commentary criticism discussion mention note observation opinion remark review animadversion annotation backtalk buzz '},
      {'name':'fa-comments','searchText':'fa-comments comments discuss conversation message chat talk commentary criticism discussion mention note observation opinion remark review animadversion annotation backtalk buzz '},
      {'name':'fa-comments-o','searchText':'fa-comments-o comments-o discuss conversation message chat talk commentary criticism discussion mention note observation opinion remark review animadversion annotation backtalk buzz '},
      {'name':'fa-compass','searchText':'fa-compass compass direction orienteering eat food location navigation find'},
      {'name':'fa-compress','searchText':'fa-compress compress media player expand squeeze shrink storten tighten reduce squash crush decrease'},
      {'name':'fa-copy','searchText':'fa-copy copy text format write edit repeat replicate reproduce transcribe clone ditto mirror duplicate'},
      {'name':'fa-credit-card','searchText':'fa-credit-card credit-card money spend'},
      {'name':'fa-crop','searchText':'fa-crop crop image photoshop modify prune shave shear chop clip snip truncate'},
      {'name':'fa-crosshairs','searchText':'fa-crosshairs crosshairs aim symbol focus'},
      {'name':'fa-css3','searchText':'fa-css3 css3 stylesheet'},
      {'name':'fa-cut','searchText':'fa-cut cut text format write edit prune shave shear chop clip snip truncate scissors'},
      {'name':'fa-cutlery','searchText':'fa-cutlery cutlery food eat symbol flatware tablewear fork knife'},
      {'name':'fa-dashboard','searchText':'fa-dashboard dashboard speed car vehicle tachometer control panel instrument console desk board mixer'},
      {'name':'fa-dedent','searchText':'fa-dedent dedent text format write edit'},
      {'name':'fa-desktop','searchText':'fa-desktop desktop computer screen monitor workstation PC'},
      {'name':'fa-dollar','searchText':'fa-dollar dollar currency money transaction economy usd cash fund payment waelth bucks coin finance funds gold riches treasure tender'},
      {'name':'fa-dot-circle-o','searchText':'fa-dot-circle-o dot-circle-o shape box voice'},
      {'name':'fa-download','searchText':'fa-download download file'},
      {'name':'fa-dribbble','searchText':'fa-dribbble dribbble social'},
      {'name':'fa-dropbox','searchText':'fa-dropbox dropbox'},
      {'name':'fa-eject','searchText':'fa-eject eject media player video audio'},
      {'name':'fa-ellipsis-h','searchText':'fa-ellipsis-h ellipsis-h dots horizontal'},
      {'name':'fa-ellipsis-v','searchText':'fa-ellipsis-v ellipsis-v dots vertical'},
      {'name':'fa-envelope','searchText':'fa-envelope envelope mail post delivery email e-mail'},
      {'name':'fa-envelope-o','searchText':'fa-envelope-o envelope-o mail post delivery email e-mail'},
      {'name':'fa-eraser','searchText':'fa-eraser eraser remove delete format write edit abolish eliminate obliterate wipe'},
      {'name':'fa-euro','searchText':'fa-euro euro currency money transaction economy eur cash fund payment waelth bucks coin finance funds gold riches treasure tender'},
      {'name':'fa-exchange','searchText':'fa-exchange exchange transfer move commerce transactionconversion dealing interchange buy sell'},
      {'name':'fa-exclamation','searchText':'fa-exclamation exclamation alert warning danger'},
      {'name':'fa-exclamation-circle','searchText':'fa-exclamation-circle exclamation-circle alert caution threatening notification sign signal suggestion'},
      {'name':'fa-exclamation-triangle','searchText':'fa-exclamation-triangle exclamation-triangle alert caution threatening notification sign signal suggestion'},
      {'name':'fa-expand','searchText':'fa-expand expand media player compress expand enlarge increase open swell bloat infate magnify stretch thicken'},
      {'name':'fa-external-link','searchText':'fa-external-link external-link box open window box'},
      {'name':'fa-external-link-square','searchText':'fa-external-link-square external-link-square box open window'},
      {'name':'fa-eye','searchText':'fa-eye eye see preview show optic inspect scan eyeball view watch stare glance look show'},
      {'name':'fa-eye-slash','searchText':'fa-eye-slash eye-slash see preview show optic inspect scan eyeball view watch stare glance look show'},
      {'name':'fa-facebook','searchText':'fa-facebook facebook social box'},
      {'name':'fa-facebook-square','searchText':'fa-facebook-square facebook-square social'},
      {'name':'fa-fast-backward','searchText':'fa-fast-backward fast-backward media player video audio'},
      {'name':'fa-fast-forward','searchText':'fa-fast-forward fast-forward media player video audio'},
      {'name':'fa-female','searchText':'fa-female female gender sex person user girl mother daughter gal gentlewoman grandmother lady madam matron sister femme miss mrs Ms she'},
      {'name':'fa-fighter-jet','searchText':'fa-fighter-jet fighter-jet vehicle aeroplane travel transport airforce'},
      {'name':'fa-file','searchText':'fa-file file text format write edit record document book data directory folder'},
      {'name':'fa-file-o','searchText':'fa-file-o file-o text format write edit record document book data directory folder'},
      {'name':'fa-file-text','searchText':'fa-file-text file-text text format write edit record document book data directory folder news'},
      {'name':'fa-file-text-o','searchText':'fa-file-text-o file-text-o text format write edit record document book data directory folder news'},
      {'name':'fa-files-o','searchText':'fa-files-o files-o text format write edit record document book data directory folder'},
      {'name':'fa-film','searchText':'fa-film film movies entertainment media cinema flick footage motion picture show'},
      {'name':'fa-filter','searchText':'fa-filter filter funnel refine clarify distill filtrate sieve siphon'},
      {'name':'fa-fire','searchText':'fa-fire fire element nature symbol blaze bonfire heat inferno campfire combustion flames flare warmth smoke searning spark tinder'},
      {'name':'fa-fire-extinguisher','searchText':'fa-fire-extinguisher fire-extinguisher safety symbol inferno campfire combustion flames flare warmth smoke searning spark tinder'},
      {'name':'fa-flag','searchText':'fa-flag flag nationality pole banner emblem'},
      {'name':'fa-flag-checkered','searchText':'fa-flag-checkered flag-checkered nationality pole stripe banner emblem'},
      {'name':'fa-flag-o','searchText':'fa-flag-o flag-o nationality pole banner emblem'},
      {'name':'fa-flask','searchText':'fa-flask flask glass science experiment symbol beaker chalice decanter vial bottle glass jar tumbler'},
      {'name':'fa-flickr','searchText':'fa-flickr flickr social box'},
      {'name':'fa-floppy-o','searchText':'fa-floppy-o floppy-o text format write edit files storage disk save'},
      {'name':'fa-folder','searchText':'fa-folder folder files directory file system operating storage binder case portfolio'},
      {'name':'fa-folder-o','searchText':'fa-folder-o folder-o file directory file system operating system storage binder case portfolio'},
      {'name':'fa-folder-open','searchText':'fa-folder-open folder-open file directory file system operating system storage binder case portfolio'},
      {'name':'fa-folder-open-o','searchText':'fa-folder-open-o folder-open-o file directory file system operating system storage binder case portfolio'},
      {'name':'fa-font','searchText':'fa-font font text format write edit typeface typesetting'},
      {'name':'fa-forward','searchText':'fa-forward forward media player video audio move'},
      {'name':'fa-foursquare','searchText':'fa-foursquare foursquare social'},
      {'name':'fa-frown-o','searchText':'fa-frown-o frown-o face smilie emoticon expression sad unhappy grim pout gloom sulk dislike disapprove'},
      {'name':'fa-gamepad','searchText':'fa-gamepad gamepad entertainment media reverse'},
      {'name':'fa-gavel','searchText':'fa-gavel gavel court legal lawyer law justice'},
      {'name':'fa-gbp','searchText':'fa-gbp gbp currency money transaction economy reverse cash fund payment waelth bucks coin finance funds gold riches treasure tender'},
      {'name':'fa-gift','searchText':'fa-gift gift present Christmas xmas bonus endowment give offerning reward'},
      {'name':'fa-github','searchText':'fa-github github develop source control   reverse'},
      {'name':'fa-github-alt','searchText':'fa-github-alt github-alt develop source control box'},
      {'name':'fa-github-square','searchText':'fa-github-square github-square develop source control'},
      {'name':'fa-gittip','searchText':'fa-gittip gittip currency money reverse cash fund payment waelth bucks coin finance funds gold riches treasure tender'},
      {'name':'fa-glass','searchText':'fa-glass glass drink liquid bottle cup jar jug chalice decanter goblet mug tumbler'},
      {'name':'fa-globe','searchText':'fa-globe globe world map navigate planet orb'},
      {'name':'fa-google-plus','searchText':'fa-google-plus google-plus social box'},
      {'name':'fa-google-plus-square','searchText':'fa-google-plus-square google-plus-square social'},
      {'name':'fa-group','searchText':'fa-group group people crowd users association club company crowd gang organisation party society'},
      {'name':'fa-h-square','searchText':'fa-h-square h-square medical medicine health'},
      {'name':'fa-hand-o-down','searchText':'fa-hand-o-down hand-o-down arrow direction empty fist grip palm'},
      {'name':'fa-hand-o-left','searchText':'fa-hand-o-left hand-o-left arrow direction empty previous fist grip palm'},
      {'name':'fa-hand-o-right','searchText':'fa-hand-o-right hand-o-right arrow direction empty next fist grip palm'},
      {'name':'fa-hand-o-up','searchText':'fa-hand-o-up hand-o-up arrow direction fist grip palm'},
      {'name':'fa-hdd-o','searchText':'fa-hdd-o hdd-o file system operating system folder storage disk'},
      {'name':'fa-headphones','searchText':'fa-headphones headphones computer media music entrainment listen earphones hear'},
      {'name':'fa-heart','searchText':'fa-heart heart body love health feeling soul affection compassion organ fitness'},
      {'name':'fa-heart-o','searchText':'fa-heart-o heart-o body love health feeling soul affection compassion organ fitness'},
      {'name':'fa-home','searchText':'fa-home home house building family local appartment cabin condo cottage dwelling hut place residence shelter domicile habitation villa'},
      {'name':'fa-hospital-o','searchText':'fa-hospital-o hospital-o medical medicine health'},
      {'name':'fa-html5','searchText':'fa-html5 html5 standard sourcecode'},
      {'name':'fa-inbox','searchText':'fa-inbox inbox mail file storage organise email e-mail'},
      {'name':'fa-indent','searchText':'fa-indent indent text format write edit'},
      {'name':'fa-info','searchText':'fa-info info information details help advice clue message tip cue notice'},
      {'name':'fa-info-circle','searchText':'fa-info-circle info-circle information details help clue message tip cue notice'},
      {'name':'fa-instagram','searchText':'fa-instagram instagram social'},
      {'name':'fa-italic','searchText':'fa-italic italic text format write edit'},
      {'name':'fa-key','searchText':'fa-key key lock open latch pass opener clue password'},
      {'name':'fa-keyboard-o','searchText':'fa-keyboard-o keyboard-o computer input accessibility PC maths'},
      {'name':'fa-laptop','searchText':'fa-laptop laptop computer notebook PC'},
      {'name':'fa-leaf','searchText':'fa-leaf leaf nature tree plant frond stalk petal'},
      {'name':'fa-lemon-o','searchText':'fa-lemon-o lemon-o nature tree plant fruit'},
      {'name':'fa-level-down','searchText':'fa-level-down level-down arrow direction move'},
      {'name':'fa-level-up','searchText':'fa-level-up level-up arrow direction move'},
      {'name':'fa-lightbulb-o','searchText':'fa-lightbulb-o lightbulb-o electricity idea power thomas edison'},
      {'name':'fa-link','searchText':'fa-link link text format write edit www web html'},
      {'name':'fa-linkedin','searchText':'fa-linkedin linkedin socila box'},
      {'name':'fa-linkedin-square','searchText':'fa-linkedin-square linkedin-square socila'},
      {'name':'fa-linux','searchText':'fa-linux linux operating system computer pc desktop laptop'},
      {'name':'fa-list','searchText':'fa-list list text format write edit'},
      {'name':'fa-list-alt','searchText':'fa-list-alt list-alt text format write edit'},
      {'name':'fa-list-ol','searchText':'fa-list-ol list-ol text format write edit'},
      {'name':'fa-list-ul','searchText':'fa-list-ul list-ul text format write edit'},
      {'name':'fa-location-arrow','searchText':'fa-location-arrow location-arrow arrow direction move'},
      {'name':'fa-lock','searchText':'fa-lock lock key access latch opener clue password'},
      {'name':'fa-long-arrow-down','searchText':'fa-long-arrow-down long-arrow-down arrow direction'},
      {'name':'fa-long-arrow-left','searchText':'fa-long-arrow-left long-arrow-left arrow direction previous'},
      {'name':'fa-long-arrow-right','searchText':'fa-long-arrow-right long-arrow-right arrow direction next'},
      {'name':'fa-long-arrow-up','searchText':'fa-long-arrow-up long-arrow-up arrow direction'},
      {'name':'fa-magic','searchText':'fa-magic magic wizard witch warlock trick'},
      {'name':'fa-magnet','searchText':'fa-magnet magnet electromagnetic science attract'},
      {'name':'fa-mail-forward','searchText':'fa-mail-forward mail-forward email e-mail'},
      {'name':'fa-mail-reply','searchText':'fa-mail-reply mail-reply email e-mail'},
      {'name':'fa-mail-reply-all','searchText':'fa-mail-reply-all mail-reply-all email e-mail'},
      {'name':'fa-male','searchText':'fa-male male gender sex boy father guy brother fellow gent gentleman grandfather he husband Mr. sir son'},
      {'name':'fa-map-marker','searchText':'fa-map-marker map-marker globe location place world country'},
      {'name':'fa-maxcdn','searchText':'fa-maxcdn maxcdn cloud'},
      {'name':'fa-medkit','searchText':'fa-medkit medkit medical health box hospital medicine'},
      {'name':'fa-meh-o','searchText':'fa-meh-o meh-o face smilie emoticon'},
      {'name':'fa-microphone','searchText':'fa-microphone microphone entertainment music sound record exchange'},
      {'name':'fa-microphone-slash','searchText':'fa-microphone-slash microphone-slash entertainment music sound record exchange'},
      {'name':'fa-minus','searchText':'fa-minus minus remove take maths exchange'},
      {'name':'fa-minus-circle','searchText':'fa-minus-circle minus-circle No-access No-entry box  exchange'},
      {'name':'fa-minus-square','searchText':'fa-minus-square minus-square No-access No-entry box  exchange'},
      {'name':'fa-minus-square-o','searchText':'fa-minus-square-o minus-square-o maths No-access No-entry  remove exchange'},
      {'name':'fa-mobile','searchText':'fa-mobile mobile phone tele communication talk exchange call contact dial buzz ring'},
      {'name':'fa-money','searchText':'fa-money money currency money transaction economy exchange cash fund payment waelth bucks coin finance funds gold riches treasure tender'},
      {'name':'fa-moon-o','searchText':'fa-moon-o moon-o plant astronomy science cresent planetoid satelite lunar orb celestial'},
      {'name':'fa-music','searchText':'fa-music music entertainment sound melody opera rock singing tune harmony hymn jazz song'},
      {'name':'fa-outdent','searchText':'fa-outdent outdent text format write edit exchange'},
      {'name':'fa-pagelines','searchText':'fa-pagelines pagelines website exchange'},
      {'name':'fa-paperclip','searchText':'fa-paperclip paperclip text format write edit exchange fastener'},
      {'name':'fa-pencil','searchText':'fa-pencil pencil edit pen write box mark wysiwyg'},
      {'name':'fa-pencil-square','searchText':'fa-pencil-square pencil-square edit pen write box wysiwyg'},
      {'name':'fa-pencil-square-o','searchText':'fa-pencil-square-o pencil-square-o edit pen write  wysiwyg'},
      {'name':'fa-phone','searchText':'fa-phone phone phone tele communication talk wysiwyg call contact dial buzz ring'},
      {'name':'fa-phone-square','searchText':'fa-phone-square phone-square phone tele communication talk call contact dial buzz ring'},
      {'name':'fa-picture-o','searchText':'fa-picture-o picture-o photo graphic wysiwyg image'},
      {'name':'fa-pinterest','searchText':'fa-pinterest pinterest social box wysiwyg image picture'},
      {'name':'fa-pinterest-square','searchText':'fa-pinterest-square pinterest-square social wysiwyg image picture'},
      {'name':'fa-plane','searchText':'fa-plane plane aeroplane aircraft fly transport wysiwyg'},
      {'name':'fa-play','searchText':'fa-play play media player video audio wysiwyg'},
      {'name':'fa-play-circle','searchText':'fa-play-circle play-circle media player video audio wysiwyg'},
      {'name':'fa-play-circle-o','searchText':'fa-play-circle-o play-circle-o media player video audio wysiwyg paste'},
      {'name':'fa-plus','searchText':'fa-plus plus add create maths  wysiwyg paste copy'},
      {'name':'fa-plus-circle','searchText':'fa-plus-circle plus-circle add create maths box'},
      {'name':'fa-plus-square','searchText':'fa-plus-square plus-square maths health add box'},
      {'name':'fa-plus-square-o','searchText':'fa-plus-square-o plus-square-o add create maths'},
      {'name':'fa-power-off','searchText':'fa-power-off power-off shutdown powerdown power off'},
      {'name':'fa-print','searchText':'fa-print print hardcopy paper wysiwyg printer fax publish'},
      {'name':'fa-puzzle-piece','searchText':'fa-puzzle-piece puzzle-piece hobby game'},
      {'name':'fa-qrcode','searchText':'fa-qrcode qrcode scan barcode'},
      {'name':'fa-question','searchText':'fa-question question help wysiwyg assist'},
      {'name':'fa-question-circle','searchText':'fa-question-circle question-circle help assist'},
      {'name':'fa-quote-left','searchText':'fa-quote-left quote-left cite reference   wysiwyg'},
      {'name':'fa-quote-right','searchText':'fa-quote-right quote-right cite reference   wysiwyg'},
      {'name':'fa-random','searchText':'fa-random random switch wysiwyg'},
      {'name':'fa-refresh','searchText':'fa-refresh refresh reload restart   wysiwyg'},
      {'name':'fa-renren','searchText':'fa-renren renren'},
      {'name':'fa-repeat','searchText':'fa-repeat repeat text format write edit wysiwyg copy'},
      {'name':'fa-reply','searchText':'fa-reply reply email respond e-mail'},
      {'name':'fa-reply-all','searchText':'fa-reply-all reply-all email respond group e-mail'},
      {'name':'fa-retweet','searchText':'fa-retweet retweet twitter social reply'},
      {'name':'fa-road','searchText':'fa-road road transport travel motor vehicle car'},
      {'name':'fa-rocket','searchText':'fa-rocket rocket transport travel motor vehicle space astronomy astronaut shuttle'},
      {'name':'fa-rotate-left','searchText':'fa-rotate-left rotate-left text format write edit wysiwyg'},
      {'name':'fa-rotate-right','searchText':'fa-rotate-right rotate-right text format write edit wysiwyg'},
      {'name':'fa-rouble','searchText':'fa-rouble rouble currency money transaction economy wysiwyg cash fund payment waelth bucks coin finance funds gold riches treasure tender'},
      {'name':'fa-rss','searchText':'fa-rss rss feed xml box feed news'},
      {'name':'fa-rss-square','searchText':'fa-rss-square rss-square feed xml feed news'},
      {'name':'fa-ruble','searchText':'fa-ruble ruble currency money transaction economy wysiwyg rub cash fund payment waelth bucks coin finance funds gold riches treasure tender'},
      {'name':'fa-rupee','searchText':'fa-rupee rupee currency money transaction economy wysiwyg inr cash fund payment waelth bucks coin finance funds gold riches treasure tender'},
      {'name':'fa-save','searchText':'fa-save save text format write edit'},
      {'name':'fa-search','searchText':'fa-search search find discover hunt investiage quest research inquest slueth examine explore inspect look probe scan scour scout seek sift inquire study'},
      {'name':'fa-search-minus','searchText':'fa-search-minus search-minus find discover remove hunt investiage quest research inquest slueth examine explore inspect look probe scan scour scout seek sift inquire study'},
      {'name':'fa-search-plus','searchText':'fa-search-plus search-plus find discover add hunt investiage quest research inquest slueth examine explore inspect look probe scan scour scout seek sift inquire study'},
      {'name':'fa-share','searchText':'fa-share share social box'},
      {'name':'fa-share-square','searchText':'fa-share-square share-square social box'},
      {'name':'fa-share-square-o','searchText':'fa-share-square-o share-square-o social'},
      {'name':'fa-shield','searchText':'fa-shield shield protect armor defense guard security'},
      {'name':'fa-shopping-cart','searchText':'fa-shopping-cart shopping-cart consumer market trolley'},
      {'name':'fa-sign-in','searchText':'fa-sign-in sign-in access login form user'},
      {'name':'fa-sign-out','searchText':'fa-sign-out sign-out access logout form user'},
      {'name':'fa-signal','searchText':'fa-signal signal graph mobile strength phone communication tele'},
      {'name':'fa-sitemap','searchText':'fa-sitemap sitemap website tree hieratchy internet www'},
      {'name':'fa-skype','searchText':'fa-skype skype communication tele talk'},
      {'name':'fa-smile-o','searchText':'fa-smile-o smile-o face smilie emoticon happy grin laugh smirk'},
      {'name':'fa-sort','searchText':'fa-sort sort A-z order reorder'},
      {'name':'fa-sort-alpha-asc','searchText':'fa-sort-alpha-asc sort-alpha-asc A-z order reorder alphabetical'},
      {'name':'fa-sort-alpha-desc','searchText':'fa-sort-alpha-desc sort-alpha-desc A-z order reorder alphabetical'},
      {'name':'fa-sort-amount-asc','searchText':'fa-sort-amount-asc sort-amount-asc A-z order reorder numeric'},
      {'name':'fa-sort-amount-desc','searchText':'fa-sort-amount-desc sort-amount-desc A-z order reorder numeric'},
      {'name':'fa-sort-asc','searchText':'fa-sort-asc sort-asc A-z order reorder alphabetical'},
      {'name':'fa-sort-desc','searchText':'fa-sort-desc sort-desc A-z order reorder alphabetical'},
      {'name':'fa-sort-down','searchText':'fa-sort-down sort-down A-z order reorder'},
      {'name':'fa-sort-numeric-asc','searchText':'fa-sort-numeric-asc sort-numeric-asc A-z order reorder numeric'},
      {'name':'fa-sort-numeric-desc','searchText':'fa-sort-numeric-desc sort-numeric-desc A-z order reorder numeric'},
      {'name':'fa-sort-up','searchText':'fa-sort-up sort-up A-z order reorder alphabetical'},
      {'name':'fa-spinner','searchText':'fa-spinner spinner loading box rotate circle'},
      {'name':'fa-square','searchText':'fa-square square shape box'},
      {'name':'fa-square-o','searchText':'fa-square-o square-o shape'},
      {'name':'fa-stack-exchange','searchText':'fa-stack-exchange stack-echange stackexchange application empty'},
      {'name':'fa-stack-exchange','searchText':'fa-stack-exchange stack-exchange social'},
      {'name':'fa-stack-overflow','searchText':'fa-stack-overflow stack-overflow social'},
      {'name':'fa-star','searchText':'fa-star star shape celestial astronomy favorite favorite planetoid'},
      {'name':'fa-star-half','searchText':'fa-star-half star-half shape celestial astronomy favorite favorite planetoid'},
      {'name':'fa-star-half-empty','searchText':'fa-star-half-empty star-half-empty shape celestial astronomy favorite favorite planetoid'},
      {'name':'fa-star-half-full','searchText':'fa-star-half-full star-half-full shape celestial astronomy favorite favorite planetoid'},
      {'name':'fa-star-half-o','searchText':'fa-star-half-o star-half-o shape celestial astronomy favorite favorite planetoid'},
      {'name':'fa-star-o','searchText':'fa-star-o star-o shape celestial astronomy favorite favorite planetoid'},
      {'name':'fa-step-backward','searchText':'fa-step-backward step-backward media player video audio move'},
      {'name':'fa-step-forward','searchText':'fa-step-forward step-forward media player video audio move'},
      {'name':'fa-stethoscope','searchText':'fa-stethoscope stethoscope medical health medicine medkit'},
      {'name':'fa-stop','searchText':'fa-stop stop media player video audio'},
      {'name':'fa-strikethrough','searchText':'fa-strikethrough strikethrough text format write edit cancel remove'},
      {'name':'fa-subscript','searchText':'fa-subscript subscript text reference'},
      {'name':'fa-suitcase','searchText':'fa-suitcase suitcase briefcase container carry briefcase case container carry storage baggage attache'},
      {'name':'fa-sun-o','searchText':'fa-sun-o sun-o star solar astronomy space celestial astronomy planetoid astronaut'},
      {'name':'fa-superscript','searchText':'fa-superscript superscript text'},
      {'name':'fa-table','searchText':'fa-table table text format write edit rows columns'},
      {'name':'fa-tablet','searchText':'fa-tablet tablet computer mobile portable'},
      {'name':'fa-tag','searchText':'fa-tag tag label mark badge button card marker pin stamp flap stub tab'},
      {'name':'fa-tasks','searchText':'fa-tasks tasks todo list progress'},
      {'name':'fa-terminal','searchText':'fa-terminal terminal command dos bash'},
      {'name':'fa-text-height','searchText':'fa-text-height text-height text format write edit'},
      {'name':'fa-text-width','searchText':'fa-text-width text-width text format write edit'},
      {'name':'fa-th','searchText':'fa-th th text format write edit'},
      {'name':'fa-th-large','searchText':'fa-th-large th-large text format write edit'},
      {'name':'fa-th-list','searchText':'fa-th-list th-list text format write edit'},
      {'name':'fa-thumb-tack','searchText':'fa-thumb-tack thumb-tack pin hand'},
      {'name':'fa-thumbs-down','searchText':'fa-thumbs-down thumbs-down hand vote empty hand'},
      {'name':'fa-thumbs-o-down','searchText':'fa-thumbs-o-down thumbs-o-down hand vote empty hand'},
      {'name':'fa-thumbs-o-up','searchText':'fa-thumbs-o-up thumbs-o-up hand vote hand'},
      {'name':'fa-thumbs-up','searchText':'fa-thumbs-up thumbs-up hand vote hand'},
      {'name':'fa-ticket','searchText':'fa-ticket ticket admission card check coupon passpoer permit receipt record voucher'},
      {'name':'fa-times','searchText':'fa-times times remove close times multiply'},
      {'name':'fa-times-circle','searchText':'fa-times-circle times-circle remove close times multiply'},
      {'name':'fa-times-circle-o','searchText':'fa-times-circle-o times-circle-o remove close times multiply'},
      {'name':'fa-tint','searchText':'fa-tint tint drop water colour color coloration glow hue tinge chroma dye hint lumunosity pigmentation stain tone'},
      {'name':'fa-toggle-down','searchText':'fa-toggle-down toggle-down arrow direction move switch knob adjust on/off'},
      {'name':'fa-toggle-left','searchText':'fa-toggle-left toggle-left arrow direction move switch knob adjust on/off'},
      {'name':'fa-toggle-right','searchText':'fa-toggle-right toggle-right arrow direction move switch knob adjust on/off'},
      {'name':'fa-toggle-up','searchText':'fa-toggle-up toggle-up arrow direction move switch knob adjust on/off'},
      {'name':'fa-trash-o','searchText':'fa-trash-o trash-o rubbish recycle bin debris junk litter rubble waste refuse'},
      {'name':'fa-trello','searchText':'fa-trello trello project team'},
      {'name':'fa-trophy','searchText':'fa-trophy trophy win award cup gold keepsake medal prize'},
      {'name':'fa-truck','searchText':'fa-truck truck vehicle transport motor carry traffic car crate freighter jeep lorry pickup rig van wagon semi wheels'},
      {'name':'fa-tumblr','searchText':'fa-tumblr tumblr social box'},
      {'name':'fa-tumblr-square','searchText':'fa-tumblr-square tumblr-square social'},
      {'name':'fa-turkish-lira','searchText':'fa-turkish-lira turkish-lira currency money transaction economy try cash fund payment waelth bucks coin finance funds gold riches treasure tender'},
      {'name':'fa-twitter','searchText':'fa-twitter twitter social box'},
      {'name':'fa-twitter-square','searchText':'fa-twitter-square twitter-square social box'},
      {'name':'fa-umbrella','searchText':'fa-umbrella umbrella rain shade brolly guard screen shelter sunshade canopy'},
      {'name':'fa-underline','searchText':'fa-underline underline text format write edit'},
      {'name':'fa-undo','searchText':'fa-undo undo text format write edit'},
      {'name':'fa-unlink','searchText':'fa-unlink unlink text format write edit'},
      {'name':'fa-unlock','searchText':'fa-unlock unlock lock access'},
      {'name':'fa-unlock-alt','searchText':'fa-unlock-alt unlock-alt lock access'},
      {'name':'fa-unsorted','searchText':'fa-unsorted unsorted arrows direction'},
      {'name':'fa-upload','searchText':'fa-upload upload file document www web'},
      {'name':'fa-user','searchText':'fa-user user person body character customer guy human individual life man woman girl somebody someone identity self hominiod'},
      {'name':'fa-user-md','searchText':'fa-user-md user-md medical health medkit medicine hospital'},
      {'name':'fa-users','searchText':'fa-users users person people group body character customer guy human individual life man woman girl somebody someone identity self hominiod association band club crowd gang organisation party'},
      {'name':'fa-video-camera','searchText':'fa-video-camera video-camera media entertainment video record'},
      {'name':'fa-vimeo-square','searchText':'fa-vimeo-square vimeo-square video social box'},
      {'name':'fa-vk','searchText':'fa-vk vk'},
      {'name':'fa-volume-down','searchText':'fa-volume-down volume-down media sound music'},
      {'name':'fa-volume-off','searchText':'fa-volume-off volume-off media sound music'},
      {'name':'fa-volume-up','searchText':'fa-volume-up volume-up media sound music'},
      {'name':'fa-weibo','searchText':'fa-weibo weibo'},
      {'name':'fa-wheelchair','searchText':'fa-wheelchair wheelchair accessibility symbol box'},
      {'name':'fa-windows','searchText':'fa-windows windows operating system crash general protection error blue screen of death'},
      {'name':'fa-won','searchText':'fa-won won currency money transaction economy krw cash fund payment waelth bucks coin finance funds gold riches treasure tender'},
      {'name':'fa-wrench','searchText':'fa-wrench wrench tool settings configure box change customise personalise customize personalize'},
      {'name':'fa-xing','searchText':'fa-xing xing social box'},
      {'name':'fa-xing-square','searchText':'fa-xing-square xing-square social'},
      {'name':'fa-yen','searchText':'fa-yen yen currency money transaction economy jpy rmb cash fund payment waelth bucks coin finance funds gold riches treasure tender'},
      {'name':'fa-youtube','searchText':'fa-youtube youtube social'},
      {'name':'fa-youtube-play','searchText':'fa-youtube-play youtube-play social video video audio'},
      {'name':'fa-youtube-square','searchText':'fa-youtube-square youtube-square social'}
    ];

  $("#loading").css("display","none");
}

(function(){var t,e=[].slice,n={}.hasOwnProperty;t=function(){function t(){var e,n;for(e=[],n=1;4>=n;n++)e.push(new t.mutablecolor(60));this.col=e,this._scheme="mono",this._distance=.5,this._web_safe=!1,this._add_complement=!1}var r,o,a,s,i,u;for(o=Array.isArray||function(t){return"[object Array]"==={}.toString.call(t)},t.SCHEMES={},u="mono monochromatic contrast triade tetrade analogic".split(/\s+/),s=0,i=u.length;i>s;s++)a=u[s],t.SCHEMES[a]=!0;return t.PRESETS={"default":[-1,-1,1,-.7,.25,1,.5,1],pastel:[.5,-.9,.5,.5,.1,.9,.75,.75],soft:[.3,-.8,.3,.5,.1,.9,.5,.75],light:[.25,1,.5,.75,.1,1,.5,1],hard:[1,-1,1,-.6,.1,1,.6,1],pale:[.1,-.85,.1,.5,.1,1,.1,.75]},t.COLOR_WHEEL={0:[255,0,0,100],15:[255,51,0,100],30:[255,102,0,100],45:[255,128,0,100],60:[255,153,0,100],75:[255,178,0,100],90:[255,204,0,100],105:[255,229,0,100],120:[255,255,0,100],135:[204,255,0,100],150:[153,255,0,100],165:[51,255,0,100],180:[0,204,0,80],195:[0,178,102,70],210:[0,153,153,60],225:[0,102,178,70],240:[0,51,204,80],255:[25,25,178,70],270:[51,0,153,60],285:[64,0,153,60],300:[102,0,153,60],315:[153,0,153,60],330:[204,0,153,80],345:[229,0,102,90]},t.prototype.colors=function(){var t,e,n,r,o,a,s,i,u,h=this;if(a=1,e=this.col[0].get_hue(),t={mono:function(){},contrast:function(){return a=2,h.col[1].set_hue(e),h.col[1].rotate(180)},triade:function(){var t;return a=3,t=60*h._distance,h.col[1].set_hue(e),h.col[1].rotate(180-t),h.col[2].set_hue(e),h.col[2].rotate(180+t)},tetrade:function(){var t;return a=4,t=90*h._distance,h.col[1].set_hue(e),h.col[1].rotate(180),h.col[2].set_hue(e),h.col[2].rotate(180+t),h.col[3].set_hue(e),h.col[3].rotate(t)},analogic:function(){var t;return a=h._add_complement?4:3,t=60*h._distance,h.col[1].set_hue(e),h.col[1].rotate(t),h.col[2].set_hue(e),h.col[2].rotate(360-t),h.col[3].set_hue(e),h.col[3].rotate(180)}},t.monochromatic=t.mono,null==t[this._scheme])throw"Unknown color scheme name: "+this._scheme;for(t[this._scheme](),o=[],n=s=0,u=a-1;u>=0?u>=s:s>=u;n=u>=0?++s:--s)for(r=i=0;3>=i;r=++i)o[4*n+r]=this.col[n].get_hex(this._web_safe,r);return o},t.prototype.colorset=function(){var t,e;for(t=r(this.colors()),e=[];t.length>0;)e.push(t.splice(0,4));return e},t.prototype.from_hue=function(t){if(null==t)throw"from_hue needs an argument";return this.col[0].set_hue(t),this},t.prototype.rgb2hsv=function(){var t,n,r,a,s,i,u,h,l,c;return h=arguments.length>=1?e.call(arguments,0):[],null!=h[0]&&o(h[0])&&(h=h[0]),u=h[0],r=h[1],t=h[2],i=Math.min.apply(Math,[u,r,t]),s=Math.max.apply(Math,[u,r,t]),n=s-i,c=s,n>0?(l=n/s,a=u===s?(r-t)/n:r===s?2+(t-u)/n:4+(u-r)/n,a*=60,a%=360,[a,l,c]):[0,0,c]},t.prototype.from_hex=function(e){var r,o,a,s,i,u,h,l,c,f,p,_,m,d,v,g,b,y,w,E,M;if(null==e)throw"from_hex needs an argument";if(!/^([0-9A-F]{2}){3}$/im.test(e))throw"from_hex("+e+") - argument must be in the form of RRGGBB";g=/(..)(..)(..)/.exec(e).slice(1,4),E=function(){var t,e,n;for(n=[],t=0,e=g.length;e>t;t++)d=g[t],n.push(parseInt(d,16));return n}(),v=E[0],a=E[1],r=E[2],l=this.rgb2hsv(function(){var t,e,n,o;for(n=[v,a,r],o=[],t=0,e=n.length;e>t;t++)f=n[t],o.push(f/255);return o}()),i=l[0],u=0,h=1e3,p=null,_=null,s=null,b=null,y=null,w=[],M=t.COLOR_WHEEL;for(f in M)n.call(M,f)&&w.push(f);for(f in w.sort(function(t,e){return t-e}))o=t.COLOR_WHEEL[w[f]],c=this.rgb2hsv(function(){var t,e,n,r;for(n=o.slice(0,3),r=[],t=0,e=n.length;e>t;t++)f=n[t],r.push(f/255);return r}()),s=c[0],s>=u&&i>=s&&(u=s,p=f),h>=s&&s>=i&&(h=s,_=f);return(0===h||h>360)&&(h=360,_=360),m=h!==u?(i-u)/(h-u):0,s=Math.round(p+m*(_-p)),s%=360,b=l[1],y=l[2],this.from_hue(s),this._set_variant_preset([b,y,b,.7*y,.25*b,1,.5*b,1]),this},t.prototype.add_complement=function(t){if(null==t)throw"add_complement needs an argument";return this._add_complement=t,this},t.prototype.web_safe=function(t){if(null==t)throw"web_safe needs an argument";return this._web_safe=t,this},t.prototype.distance=function(t){if(null==t)throw"distance needs an argument";if(0>t)throw"distance("+t+") - argument must be >= 0";if(t>1)throw"distance("+t+") - argument must be <= 1";return this._distance=t,this},t.prototype.scheme=function(e){if(null==e)throw"scheme needs an argument";if(null==t.SCHEMES[e])throw"'"+e+"' isn't a valid scheme name";return this._scheme=e,this},t.prototype.variation=function(e){if(null==e)throw"variation needs an argument";if(null==t.PRESETS[e])throw"'$v' isn't a valid variation name";return this._set_variant_preset(t.PRESETS[e]),this},t.prototype._set_variant_preset=function(t){var e,n,r;for(r=[],e=n=0;3>=n;e=++n)r.push(this.col[e].set_variant_preset(t));return r},r=function(t){var e,n,o;if(null==t||"object"!=typeof t)return t;if(t instanceof Date)return new Date(t.getTime());if(t instanceof RegExp)return e="",null!=t.global&&(e+="g"),null!=t.ignoreCase&&(e+="i"),null!=t.multiline&&(e+="m"),null!=t.sticky&&(e+="y"),RegExp(t.source,e);o=new t.constructor;for(n in t)o[n]=r(t[n]);return o},t.mutablecolor=function(){function e(e){if(null==e)throw"No hue specified";this.saturation=[],this.value=[],this.base_red=0,this.base_green=0,this.base_blue=0,this.base_saturation=0,this.base_value=0,this.set_hue(e),this.set_variant_preset(t.PRESETS["default"])}return e.prototype.hue=0,e.prototype.saturation=[],e.prototype.value=[],e.prototype.base_red=0,e.prototype.base_green=0,e.prototype.base_saturation=0,e.prototype.base_value=0,e.prototype.get_hue=function(){return this.hue},e.prototype.set_hue=function(e){var n,r,o,a,s,i,u,h,l,c;n=function(t,e,n){return t+Math.round((e-t)*n)},this.hue=Math.round(e%360),s=this.hue%15+(this.hue-Math.floor(this.hue)),c=s/15,i=this.hue-Math.floor(s),u=(i+15)%360,o=t.COLOR_WHEEL[i],a=t.COLOR_WHEEL[u],h={red:0,green:1,blue:2,value:3};for(r in h)l=h[r],this["base_"+r]=n(o[l],a[l],c);return this.base_saturation=n(100,100,c)/100,this.base_value/=100},e.prototype.rotate=function(t){var e;return e=(this.hue+t)%360,this.set_hue(e)},e.prototype.get_saturation=function(t){var e,n;return n=this.saturation[t],e=0>n?-n*this.base_saturation:n,e>1&&(e=1),0>e&&(e=0),e},e.prototype.get_value=function(t){var e,n;return n=this.value[t],e=0>n?-n*this.base_value:n,e>1&&(e=1),0>e&&(e=0),e},e.prototype.set_variant=function(t,e,n){return this.saturation[t]=e,this.value[t]=n},e.prototype.set_variant_preset=function(t){var e,n,r;for(r=[],e=n=0;3>=n;e=++n)r.push(this.set_variant(e,t[2*e],t[2*e+1]));return r},e.prototype.get_hex=function(t,e){var n,r,o,a,s,i,u,h,l,c,f,p,_,m,d,v,g;for(i=Math.max.apply(Math,function(){var t,e,n,o;for(n=["red","green","blue"],o=[],t=0,e=n.length;e>t;t++)r=n[t],o.push(this["base_"+r]);return o}.call(this)),u=Math.min.apply(Math,function(){var t,e,n,o;for(n=["red","green","blue"],o=[],t=0,e=n.length;e>t;t++)r=n[t],o.push(this["base_"+r]);return o}.call(this)),p=255*(0>e?this.base_value:this.get_value(e)),c=0>e?this.base_saturation:this.get_saturation(e),s=i>0?p/i:0,h=[],g=["red","green","blue"],_=0,d=g.length;d>_;_++)r=g[_],l=Math.min.apply(Math,[255,Math.round(p-(p-this["base_"+r]*s)*c)]),h.push(l);for(t&&(h=function(){var t,e,r;for(r=[],t=0,e=h.length;e>t;t++)n=h[t],r.push(51*Math.round(n/51));return r}()),o="",m=0,v=h.length;v>m;m++)a=h[m],f=a.toString(16),2>f.length&&(f="0"+f),o+=f;return o},e}(),t}(),"undefined"!=typeof module&&null!==module&&null!=module.exports?module.exports=t:"function"==typeof define&&define.amd?define([],function(){return t}):window.ColorScheme=t}).call(this);